clinet/urls.py
from django.urls import path
from clinet import views




urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('login/', views.dashboard_login, name="login"),
    path('logout/', views.dashboard_logout, name="logout"),

    path('category_list/', views.category_list, name="category_list"),
    path('category_create/', views.category_create, name="category_create"),
    path('<int:pk>category_edit/', views.category_edit, name="category_edit"),
    path('<int:pk>/category_delete/', views.category_delete, name="category_delete"),

    path('groups_list/', views.groups_list, name="groups_list"),
    path('groups_create/', views.groups_create, name="groups_create"),
    path('<int:pk>/groups_edit/', views.groups_edit, name="groups_edit"),
    path('<int:pk>/groups_delete/', views.groups_delete, name="groups_delete"),

    path('students_guruh/<int:id>/', views.students_guruh, name="students_guruh"),

    path('students_list/', views.students_list, name="students_list"),
    path('students_create/', views.students_create, name="students_create"),
    path('<int:pk>/students_edit/', views.students_edit, name="students_edit"),
    path('<int:pk>/students_delete/', views.students_delete, name="students_delete"),


    path('blog_list/', views.blog_list, name="blog_list"),
    path('blog_create/', views.blog_create, name="blog_create"),
    path('<int:pk>/blog_edit/', views.blog_edit, name="blog_edit"),
    path('<int:pk>/blog_delete/', views.blog_delete, name="blog_delete"),

    path('year_list/', views.year_list, name="year_list"),
    path('year_create/', views.year_create, name="year_create"),
    path('<int:pk>/year_edit/', views.year_edit, name="year_edit"),
    path('<int:pk>/year_delete/', views.year_delete, name="year_delete"),

    path('davomat_list/', views.davomat_list, name="davomat_list"),
    path('davomat_create/', views.davomat_create, name="davomat_create"),
    path('<int:pk>/davomat_edit/', views.davomat_edit, name="davomat_edit"),
    path('<int:pk>/davomat_delete/', views.davomat_delete, name="davomat_delete"),


    path('molya_list_molya/<int:id>/', views.molya_list_molya, name="molya_list_molya"),

    path('molya_list/', views.molya_list, name="molya_list"),
    path('molya_create/', views.molya_create, name="molya_create"),
    path('<int:pk>/molya_edit/', views.molya_edit, name="molya_edit"),
    path('<int:pk>/molya_delete/', views.molya_delete, name="molya_delete"),

    path('molya_fanta/<int:id>/', views.molya_fanta, name="molya_fanta"),

    path('molya_fanta_list/', views.molya_fanta_list, name="molya_fanta_list"),
    path('molya_fanta_create/', views.molya_fanta_create, name="molya_fanta_create"),
    path('<int:pk>/molya_fanta_edit/', views.molya_fanta_edit, name="molya_fanta_edit"),
    path('<int:pk>/molya_fanta_delete/', views.molya_fanta_delete, name="molya_fanta_delete")

]

ics_crm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

main/urls.py
from django.urls import path, include
from main.views import index, course_list, blog_list

app_name="main"

urlpatterns = [
    path('', index, name='index'),
    path('clinet/', include('clinet.urls')),
    path('course/', course_list, name='course'),
    path('blog/', blog_list, name='blog')
]

templates/dashboard/students/form.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block content %}
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Students</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{% url 'main:index' %}">Saytga oʻtish</a></li>
                        <li class="breadcrumb-item active">Students</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-primary">

                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="card-body">
                                <div class="form-group">
                                    <label>Guruh Nomi</label>
                                    {{ form.groups }}
                                </div>
                                <div class="form-group">
                                    <label>O'quvchi Fam</label>
                                    {{ form.last_name }}
                                </div>

                                <div class="form-group">
                                    <label>O'quvchi Ism</label>
                                    {{ form.name }}
                                </div>

                                <div class="form-group">
                                    <label>O'quvchi Nomeri</label>
                                    {{ form.number }}
                                </div>

                                <div class="form-group">
                                    <label>O'quvchi Kelgan vaqti</label>
                                    {{ form.date }}
                                </div>
                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Saqlash</button>
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/dashboard/students/list.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block content %}
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>O'quvchilar</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{% url 'main:index' %}">Saytga oʻtish</a></li>
                        <li class="breadcrumb-item active">O'quvchilar</li>
                    </ol>
                </div>
            </div>

        </div>
    </section>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            {% for i in guruh %}
                                <a href="{% url 'main:students_guruh' i.id %}">
                                    <button type="button" class="btn btn-success"><b>{{ i.name }}</b></button>
                                </a>
                            {% endfor %}
                            <div class="card-tools">
                                <a href="{% url 'main:students_create' %}">
                                    <div class="btn btn-block btn-outline-success">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                             fill="currentColor" class="bi bi-plus-lg" viewBox="0 0 16 16">
                                            <path d="M8 0a1 1 0 0 1 1 1v6h6a1 1 0 1 1 0 2H9v6a1 1 0 1 1-2 0V9H1a1 1 0 0 1 0-2h6V1a1 1 0 0 1 1-1z"/>
                                        </svg>
                                        Qoʻshish
                                    </div>
                                </a>
                            </div>
                        </div>

                        <div class="card-body table-responsive p-0">
                            <table class="table table-hover text-nowrap">
                                <thead>
                                <tr>
                                    <th>№</th>
                                    <th>Guruh Nomi</th>
                                    <th>Fam</th>
                                    <th>Ism</th>
                                    <th>Nomeri</th>
                                    <th>Kelgan vaqti</th>
                                    <th>Taxrirlash</th>
                                    <th>Oʻchrish</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for i in students %}
                                    <tr>
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ i.groups }}</td>
                                        <td>{{ i.last_name }}</td>
                                        <td>{{ i.name }}</td>
                                        <td>{{ i.number }}</td>
                                        <td>{{ i.date }}</td>
                                        <td><a href="{% url 'main:students_edit' pk=i.id %}">
                                            <div class=" m-6 btn btn-block btn-outline-warning">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                                     fill="currentColor" class="bi bi-pencil-square"
                                                     viewBox="0 0 16 16">
                                                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                                    <path fill-rule="evenodd"
                                                          d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                                                </svg>
                                                Taxrirlasha
                                            </div>
                                        </a></td>
                                        <td><a href="#">
{#                                            <div class="m-6 btn btn-block btn-outline-danger ">#}
{##}
{#                                                Oʻchrish#}
{#                                            </div>#}
                                            <button type="button" class="btn btn-outline-danger" data-toggle="modal" data-target="#exampleModal">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                                     fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                                    <path fill-rule="evenodd"
                                                          d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                                </svg>
                                                Oʻchrish
                                            </button>
                                        </a></td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
            </div>
        </div>
    </section>



    <!-- Button trigger modal -->


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Talabani Guruhdan ketish sababini yozing</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <p><b>Guruh nomi:</b> <span><i><b style="color: darkgreen">Front-end</b></i></span></p>
          <p><b>Talaba ism:</b> <span><i><b style="color: darkgreen">hello</b></i></span></p>
          <p><b>Talaba telefon raqami:</b> <span><i><b style="color: darkgreen">787878</b></i></span></p>
        <form>
        <div class="form-group">
            <label for="exampleFormControlTextarea1">Iltimos Sababni yozib qoldiring!!</label>
            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
        </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-info" data-dismiss="modal">O'chrish va telegram guruhga jo'natish</button>
        <button type="button" class="btn btn-danger">Saqlib O'chrish</button>
      </div>
    </div>
  </div>
</div>


{% endblock %}

templates/dashboard/students/studet_groups.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block content %}
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>O'quvchilar</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{% url 'main:index' %}">Saytga oʻtish</a></li>
                        <li class="breadcrumb-item active">O'quvchilar</li>
                    </ol>
                </div>
            </div>

        </div>
    </section>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                           {% for i in guruh %}
                                <a href="{% url 'main:students_guruh' i.id %}">
                                    <button type="button" class="btn btn-success"><b>{{ i.name }}</b></button>
                                </a>
                            {% endfor %}
                            <div class="card-tools">
                                <a href="{% url 'main:students_create' %}">
                                    <div class="btn btn-block btn-outline-success">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                             fill="currentColor" class="bi bi-plus-lg" viewBox="0 0 16 16">
                                            <path d="M8 0a1 1 0 0 1 1 1v6h6a1 1 0 1 1 0 2H9v6a1 1 0 1 1-2 0V9H1a1 1 0 0 1 0-2h6V1a1 1 0 0 1 1-1z"/>
                                        </svg>
                                        Qoʻshish
                                    </div>
                                </a>
                            </div>
                        </div>

                        <div class="card-body table-responsive p-0">
                            <table class="table table-hover text-nowrap">
                                <thead>
                                <tr>
                                    <th>№</th>
                                    <th>Guruh Nomi</th>
                                    <th>Fam</th>
                                    <th>Ism</th>
                                    <th>Nomeri</th>
                                    <th>Kelgan vaqti</th>
                                    <th>Taxrirlash</th>
                                    <th>Oʻchrish</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for i in students_guruh %}
                                    <tr>
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ i.groups }}</td>
                                        <td>{{ i.last_name }}</td>
                                        <td>{{ i.name }}</td>
                                        <td>{{ i.number }}</td>
                                        <td>{{ i.date }}</td>
                                        <td><a href="{% url 'main:students_edit' pk=i.id %}">
                                            <div class=" m-6 btn btn-block btn-outline-warning">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                                     fill="currentColor" class="bi bi-pencil-square"
                                                     viewBox="0 0 16 16">
                                                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                                    <path fill-rule="evenodd"
                                                          d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                                                </svg>
                                                Taxrirlash
                                            </div>
                                        </a></td>
                                        <td><a href="{% url 'main:students_delete' pk=i.id %}">
                                            <div class="m-6 btn btn-block btn-outline-danger ">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                                     fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                                    <path fill-rule="evenodd"
                                                          d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                                </svg>
                                                Oʻchrish
                                            </div>
                                        </a></td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
            </div>
        </div>
    </section>
{% endblock %}