clinet/urls.py
from django.urls import path
from clinet import views




urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('login/', views.dashboard_login, name="login"),
    path('logout/', views.dashboard_logout, name="logout"),

    path('category_list/', views.category_list, name="category_list"),
    path('category_create/', views.category_create, name="category_create"),
    path('<int:pk>category_edit/', views.category_edit, name="category_edit"),
    path('<int:pk>/category_delete/', views.category_delete, name="category_delete"),

    path('groups_list/', views.groups_list, name="groups_list"),
    path('groups_create/', views.groups_create, name="groups_create"),
    path('<int:pk>/groups_edit/', views.groups_edit, name="groups_edit"),
    path('<int:pk>/groups_delete/', views.groups_delete, name="groups_delete"),

    path('students_guruh/<int:id>/', views.students_guruh, name="students_guruh"),

    path('students_list/', views.students_list, name="students_list"),
    path('students_create/', views.students_create, name="students_create"),
    path('<int:pk>/students_edit/', views.students_edit, name="students_edit"),
    path('<int:pk>/students_delete/', views.students_delete, name="students_delete"),


    path('blog_list/', views.blog_list, name="blog_list"),
    path('blog_create/', views.blog_create, name="blog_create"),
    path('<int:pk>/blog_edit/', views.blog_edit, name="blog_edit"),
    path('<int:pk>/blog_delete/', views.blog_delete, name="blog_delete"),

    path('year_list/', views.year_list, name="year_list"),
    path('year_create/', views.year_create, name="year_create"),
    path('<int:pk>/year_edit/', views.year_edit, name="year_edit"),
    path('<int:pk>/year_delete/', views.year_delete, name="year_delete"),

    path('davomat_list/', views.davomat_list, name="davomat_list"),
    path('davomat_create/', views.davomat_create, name="davomat_create"),
    path('<int:pk>/davomat_edit/', views.davomat_edit, name="davomat_edit"),
    path('<int:pk>/davomat_delete/', views.davomat_delete, name="davomat_delete"),


    path('molya_list_molya/<int:id>/', views.molya_list_molya, name="molya_list_molya"),

    path('molya_list/', views.molya_list, name="molya_list"),
    path('molya_create/', views.molya_create, name="molya_create"),
    path('<int:pk>/molya_edit/', views.molya_edit, name="molya_edit"),
    path('<int:pk>/molya_delete/', views.molya_delete, name="molya_delete"),

    path('molya_fanta/<int:id>/', views.molya_fanta, name="molya_fanta"),

    path('molya_fanta_list/', views.molya_fanta_list, name="molya_fanta_list"),
    path('molya_fanta_create/', views.molya_fanta_create, name="molya_fanta_create"),
    path('<int:pk>/molya_fanta_edit/', views.molya_fanta_edit, name="molya_fanta_edit"),
    path('<int:pk>/molya_fanta_delete/', views.molya_fanta_delete, name="molya_fanta_delete")

]

ics_crm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

main/urls.py
from django.urls import path, include
from main.views import index, course_list, blog_list

app_name="main"

urlpatterns = [
    path('', index, name='index'),
    path('clinet/', include('clinet.urls')),
    path('course/', course_list, name='course'),
    path('blog/', blog_list, name='blog')
]

templates/dashboard/base.html
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Dashboard_CRM</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'dashboard/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bootstrap 4 -->
  <link rel="stylesheet" href="{% static 'dashboard/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dashboard/css/adminlte.min.css' %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static 'dashboard/plugins/overlayScrollbars/css/overlayScrollbarsrs.min.css' %}">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{% static 'dashboard/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">

</head>
<body class="hold-transition sidebar-mini layout-fixed">
  <div class="wrapper" style="min-height: 1342.88px;">

    {% include 'dashboard/navbar.html' %}
    <div class="content-wrapper" style="min-height: 1342.88px;">
      {% block content %}{% endblock %}
    </div>
  </div>

<!-- jQuery -->
<script src="{% static 'dashboard/plugins/jquery/jquery.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'dashboard/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{% static 'dashboard/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dashboard/js/adminlte.js' %}"></script>
  <script src="{% static 'dashboard/plugins/summernote/summernote-bs4.min.js' %}"></script>
<script src="{% static 'dashboard/dist/js/demo.js' %}"></script>
{% block javascript %}{% endblock %}
</body>
</html>

templates/dashboard/index.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block content %}
{% endblock %}
{% block javascript %}
{% endblock %}

templates/dashboard/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>Admin</title>

      <!-- Google Font: Source Sans Pro -->
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
      <!-- Font Awesome -->
      <link rel="stylesheet" href="{% static 'dashboard/plugins/fontawesome-free/css/all.min.css' %}">
      <!-- icheck bootstrap -->
      <link rel="stylesheet" href="{% static 'dashboard/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
      <!-- Theme style -->
      <link rel="stylesheet" href="{% static 'dashboard/css/adminlte.min.css' %}">
    </head>
    <body class="hold-transition login-page">
        <div class="login-box">
          <div class="card card-outline card-primary">
            <div class="card-header text-center">
                <a href="{% url 'main:dashboard' %}" class="h1"><b>ADMIN</b></a>
            </div>
            <div class="card-body">
              <p class="login-box-msg">Kirish</p>

              <form method="post">
                  {% csrf_token %}
                <div class="input-group mb-3">
                  <input type="text" class="form-control" name="username" placeholder="Username">
                  <div class="input-group-append">
                    <div class="input-group-text">
                      <span class="fas fa-user"></span>
                    </div>
                  </div>
                </div>
                <div class="input-group mb-3">
                  <input type="password" class="form-control" name="password" placeholder="Password">
                  <div class="input-group-append">
                    <div class="input-group-text">
                      <span class="fas fa-lock"></span>
                    </div>
                  </div>
                </div>
                <div class="row">
                    <div class="col-12">
                     <button type="submit" class="btn btn-primary btn-block">Kirish</button>
                    </div>
                </div>
              </form>
            </div>
          </div>
        </div>
    <script src="{% static 'dashboard/plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'dashboard/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dashboard/js/adminlte.min.js' %}"></script>
    </body>
</html>

templates/dashboard/navbar.html
{% load static %}

<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{% url 'main:dashboard' %}" class="nav-link {{ d_active }}">ICA_CRM</a>
        </li>
    </ul>
</nav>

<aside class="main-sidebar sidebar-dark-primary elevation-4">

    <a href="{% url 'main:dashboard' %}" class="brand-link">
        <img src="{% static 'dashboard/img/AdminLTELogo.png' %}" alt="AdminLTE Logo"
             class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light"><b>ICA_CRM</b></span>
    </a>

    <div class="sidebar">

        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{% static 'dashboard/img/user2-160x160.jpg' %}" class="img-circle elevation-2"
                     alt="User Image">
            </div>
            <div class="info">
                <a href="" class="d-block">{{ user.username }}</a>
            </div>
        </div>
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-item">
                    <a href="{% url 'main:category_list' %}" class="nav-link {{ c_active }}">
                        <i class="nav-icon far fa-image"></i>
                        <p>Kurs</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'main:groups_list' %}" class="nav-link {{ g_active }}">
                        <i class="nav-icon far fa-image"></i>
                        <p>Guruhlar</p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="{% url 'main:students_list' %}" class="nav-link {{ s_active }}">
                        <i class="nav-icon far fa-image"></i>
                        <p>Talaba</p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="{% url 'main:blog_list' %}" class="nav-link {{ b_active }}">
                        <i class="nav-icon far fa-image"></i>
                        <p>Blog</p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="{% url 'main:year_list' %}" class="nav-link {{ y_active }}">
                        <i class="nav-icon far fa-image"></i>
                        <p>Oylar</p>
                    </a>
                </li>


                <li class="nav-item">
                    <a href="{% url 'main:davomat_list' %}" class="nav-link {{ d_active }}">
                        <i class="nav-icon far fa-image"></i>
                        <p>Davomat</p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="{% url 'main:molya_fanta_list' %}" class="nav-link {{ f_active }}">
                        <i class="nav-icon far fa-image"></i>
                        <p>Molya</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'main:logout' %}" class="nav-link">
                        <i class="nav-icon far fa-image "></i>
                        <i class="fa-sign-out"></i>
                        <p>Roʻyxatdan chiqish</p>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</aside>